### PR TITLE
Mocking improvements

### PR DESCRIPTION
**Pull request by bryceschober**
Features:
- Add optional support for incrementally-built stub programs
- Provide suggestion in README for using bats-file for better mock isolation
- Fail (and provide debug output) when extra unexpected arguments are passed to mock
- Support stubbing apps/scripts with '.' in names

@lox @jasonkarns

1. Please consider merging these forks if possible, to help the bats community stay unified and up-to-date. I definitely ran into issues with https://github.com/jasonkarns/bats-mock that were fixed with https://github.com/lox/bats-mock.

2. Please consider adding these optional features to bats-mock. See the updates to the README.md for justification and examples.

### CODE REVIEW

**Comment by lox** [comment]
I would happily merge this fork, or hand it over to the bats-core folks. I forked this purely to fix these issues.

**Comment by bryceschober** [comment]
I also added a suggestion to the user for better fail-safe usage of bats-mock in combination with bats-file.

@lox Are these changes acceptable for merging? Is there anything else I can do for you?

**Comment by lox** [comment]
Interesting idea @bryceschober! What if instead of being an option, it was the default? I hate how `bats-mock` parses the stub specification string, it ends up with so many bugs and all sorts of issues with quoting and escaping.

What if you could do something like:

```bash

stub [ apt-get update -q ] -> "exit 0"
stub [ apt-get install -y software-properties-common ] -> "echo installed!"
stub [ apt-get update -q ] -> "exit 0"
stub [ apt-get install -y myfancypackage ] -> "exit 0"
stub [ apt-add-repository -y "ppa:/myfancystuff/ppa" ] -> "exit 0"

# Run stuff here
# Checks go here...

unstub apt-get
unstub apt-add-repository
```

🤔

**Comment by lox** [comment]
There is also https://github.com/grayhemp/bats-mock by @grayhemp that I've been keeping an eye on!

**Comment by bryceschober** [comment]
Again, I've added another feature to this ongoing PR. @lox could we get this merged?

**Comment by lox** [comment]
Probably not as-is @bryceschober. There is a lot going on here and I'm not sure I'm keen on the incremental stubbing as-implemented. 

I'd be happy to take some of the smaller stuff as different PR's though.

**Comment by bryceschober** [comment]
OK @lox, I'll re-submit as separate PRs.

I have another feature coming too: Optionally turning on a helpful subset of debug output on error in any stub.

**Pull request closed without merging**
