### PR TITLE
Use eval for parsing patterns

### PR DESCRIPTION
**Pull request by lox**
Seems I broke things with #4 🤔 This goes back to using eval, as it will handle more things and I don't think the security implications are concerning. 

Also adds some basic tests to avoid repeating this.

### CODE REVIEW

**Comment by lox** [comment]
Still doesn't really gracefully handle parse errors.

**Comment by Flamefire** [comment]
I settled with the same solution: https://github.com/jasonkarns/bats-mock/pull/18

So +1 for this

**Comment by lox** [comment]
I feel like we should pool our efforts @Flamefire :D

**Comment by Flamefire** [comment]
Sure :)

**Comment by Flamefire** [comment]
To get this going I'd suggest to get this into a better shape. I started with that in my fork: https://github.com/Flamefire/bats-mock

I added all my fixes and enhancements as well as npm packaging and CI to the master branch. We should decide, which repo should become the "official" one and add collaborators so it doesn't die. @jasonkarns seems to be gone and there are many forks around with similar fixes. There is even almost a rewrite at https://github.com/norwoodj/bats-mock which I like for its clean code, but it seems also inactive. But I'd like to incorporate the ides from there. IMO all these indirect variables are a pain to work with

**Pull request merged**
